INSERT INTO roles VALUES (1,'ROLE_USER');
INSERT INTO roles VALUES (2,'ROLE_ADMIN');
INSERT INTO users VALUES (1,'admin', '$2a$11$iZEbj0X9ypdXODxwdkYgPuLBcV8FCxToD.7A.6YqrEXpEOnq7BqF.', 'admin@localhost.ru',true , NULL, NULL );
INSERT INTO genres VALUES (1,'Ужасы');
INSERT INTO genres VALUES (2,'Экшн');
INSERT INTO genres VALUES (3,'Боевик');
INSERT INTO genres VALUES (4,'Детектив');
INSERT INTO genres VALUES (5,'Документальный');
INSERT INTO genres VALUES (6,'Драма');
INSERT INTO genres VALUES (7,'Комедия');
INSERT INTO genres VALUES (8,'Криминал');
INSERT INTO genres VALUES (9,'Мелодрама');
INSERT INTO genres VALUES (10,'Мультфильм');
INSERT INTO genres VALUES (11,'Мюзикл');
INSERT INTO genres VALUES (12,'Приключения');
INSERT INTO genres VALUES (13,'Триллер');
INSERT INTO genres VALUES (14,'Фантастика');
INSERT INTO genres VALUES (15,'Фильм-нуар');
INSERT INTO genres VALUES (16,'Фэнтези');
INSERT INTO genres VALUES (17,'Вестерн');
INSERT INTO genres VALUES (18,'Аниме');
INSERT INTO user_roles VALUES (1,2);
INSERT INTO room VALUES (1,'обычный');
INSERT INTO room VALUES (2,'обычный');
INSERT INTO room VALUES (3,'обычный');
INSERT INTO row VALUES(1,1,15);
INSERT INTO row VALUES(2,2,15);
INSERT INTO row VALUES(3,3,15);
INSERT INTO row VALUES(4,1,15);
INSERT INTO row VALUES(5,2,15);
INSERT INTO row VALUES(6,3,15);
INSERT INTO row VALUES(7,1,15);
INSERT INTO row VALUES(8,2,15);
INSERT INTO row VALUES(9,3,15);
INSERT INTO row VALUES(10,1,15);
INSERT INTO row VALUES(11,1,14);
INSERT INTO row VALUES(12,1,12);
INSERT INTO row VALUES(13,1,10);